export const STORAGE_KEY = "YMCX_ADMIN";
export const PROJECT_CONFIG_KEY = "PROJECT_CONFIG"; 
export const ACCESS_TOKEN_KEY = "ACCESS_TOKEN"
export const MULTIPLE_TABS_KEY = "MULTIPLE_TABS"
export const TABS_ROUTES_KEY = 'TABS_ROUTES'; // 标签页