export interface tableDataItem {
  operationCompanyVehicleId?: string | null;
  plageNumber: null | string;
  brand: null | string;
  carSeies: null | string;
  color: null | string;
  carType: null | string;
  companyName: string | null;
  createTime: string | null;
  distance: string | null;
  plate: null | string;
  vehiclesType: null | string;
  vehicleState: null | number;
  remark: null | string;
  fuelType: null | string; 
  engineNumber: null | string;
  vin: null | string;
  engineDisplacement: null | string;
  drivingPermitType: null | string;
  vehiclesDate: null | string;
}
